# Generated by Django 6.1 on 2026-09-09 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.TextField(null=True)),
                ('category', models.CharField(choices=[('ai-engineering', 'Internship'), ('mobile-development', 'Research'), ('web-development', 'Volunteer'), ('backend-development', 'Part-Time'), ('general', 'Freelance')], max_length=20)),
                ('project_url', models.TextField(null=True)),
            ],
        ),
    ]
