# Generated by Django 6.1 on 2026-09-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai-engineering', 'AI Engineering'), ('mobile-development', 'Mobile Development'), ('web-development', 'Web Development'), ('backend-development', 'Backend Development'), ('general', 'General')], max_length=20),
        ),
    ]
